## FILE: docker-compose.yml
version: '3'
#########################################################
## DOCKER NETWORK
#########################################################
networks:
  formio-network:
    driver: bridge
services:
  ##############################################
  ## PROXY
  ##############################################
  proxy:
    container_name: proxy
    image: ryanformio/formio-proxy
    ports:
      - 3000:80
    links:
      - api-server
      - pdf-server
    networks:
      - formio-network
    ## Comment out if running locally, for streaming logs to Azure
    # logging:
    #   driver: stdout
  ##############################################
  ## API SERVER
  ##############################################
  api-server:
    container_name: api-server
    image: formio/formio-enterprise:${API_TAG}
    environment:
      PORT: 3000
      DEBUG: "formio.*"
      PDF_SERVER: http://pdf-server:4005
      PORTAL_ENABLED: 1
      MONGO: ${MONGO}
      LICENSE_KEY: ${LICENSE_KEY}
      ADMIN_KEY: ${ADMIN_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
      DB_SECRET: ${DB_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - formio-network
    ## Comment out if running locally, for streaming logs to Azure
    # logging:
    #   driver: stdout
  ##############################################
  ## PDF SERVER
  ##############################################
  pdf-server:
    container_name: pdf-server
    image: formio/pdf-server:${PDF_TAG}
    ports:
      - "4005:4005"
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      MONGO: ${MONGO}
      FORMIO_AZURE_CONNECTION_STRING: ${FORMIO_AZURE_CONNECTION_STRING}
      FORMIO_AZURE_CONTAINER: ${FORMIO_AZURE_CONTAINER}
      FORMIO_PDF_PORT: 4005
      DEBUG: "pdf.*"
    networks:
      - formio-network
    ## Comment out if running locally, for streaming logs to Azure
    # logging:
    #   driver: stdout