#########################################################
## Repository Details
##
## https://github.com/ryanformio/formio-enterprise-on-azure-app-service
#########################################################
version: '3'
##############################################
## DOCKER NETWORK
##############################################
networks:
  formio-dev:
    driver: bridge
services:
  ##############################################
  ## PROXY
  ##############################################
  proxy:
    container_name: proxy
    image: ryanformio/formio-proxy
    ports:
      - 80:80
    links:
      - api-server
      - pdf-server
    networks:
      - formio-dev
    logging:
      driver: stdout
  ##############################################
  ## API SERVER
  ##############################################
  api-server:
    container_name: api-server
    image: formio/formio-enterprise:8.0.0-rc.35
    logging:
      driver: stdout
    environment:
      DEBUG: "formio.*"
      PDF_SERVER: http://pdf-server:4005
      PORTAL_ENABLED: 1
      PORT: 3000
      MONGO: ${MONGO}
      LICENSE_KEY: ${LICENSE_KEY}
      ADMIN_KEY: ${ADMIN_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
      DB_SECRET: ${DB_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - formio-dev
  ##############################################
  ## PDF SERVER
  ##############################################
  pdf-server:
    container_name: pdf-server
    image: formio/pdf-server:5.0.0-rc.3
    logging:
      driver: stdout
    ports:
      - "4005:4005"
    environment:
      FORMIO_PDF_PORT: 4005
      DEBUG: "pdf.*"
      LICENSE_KEY: ${LICENSE_KEY}
      MONGO: ${MONGO}
      FORMIO_AZURE_CONNECTION_STRING: ${FORMIO_AZURE_CONNECTION_STRING}
      FORMIO_AZURE_CONTAINER: ${FORMIO_AZURE_CONTAINER}
    networks:
      - formio-dev